name = "toplista-api"
main = "src/api-worker.js"
compatibility_date = "2024-01-01"

[vars]
ORIGIN = "https://toplista.mk"
CORS_ORIGINS = "https://toplista.mk,https://www.toplista.mk,https://www.najjak.com,https://martinpetkovski.github.io,http://localhost,http://127.0.0.1:5500"
